export const campusData = [
  {
    src: "https://www.mohawkcollege.ca/sites/default/files/Campuses%20and%20Maps/ff-fennell-exterior-820x370.jpg",
    h2: "Mohawk College Fennell Campus (FF)",
    h3: "About Fennell Campus:",
    p: "Located at the edge of the Hamilton escarpment, Fennell Campus has undergone the largest renovation in Mohawk history. Re-designed as a welcoming place to live and learn, the renewal has created a modernized space while enhancing energy efficiency, barrier-free access and more. Whether you choose to live in residence or in an off-campus neighbourhood, at Fennell Campus you’ll feel at home.",
    lat: 43.239419208231936,
    lng: -79.88828661570639,
  },
  {
    src: "https://www.mohawkcollege.ca/sites/default/files/Marketing%20and%20Communications/images/Centre_for_Aviation_Technology-800x533.jpg",
    h2: "Centre for Aviation Technology",
    h3: "About Aviation Campus:",
    p: "Mohawk’s new Centre for Aviation Technology at Hamilton International Airport (YHM) is home to classrooms, labs and hangar space for Mohawk's Aviation Technician programs.",
    lat: 43.180247,
    lng: -79.913732,
  },
  {
    src: "https://www.mohawkcollege.ca/sites/default/files/Marketing%20and%20Communications/images/campus-iahs-exterior-2019.jpg",
    h2: "Institute for Applied Health Sciences at McMaster (IH)",
    h3: "About the Institute for Applied Health Sciences (IAHS):",
    p: "Home to six hospitals and a cancer centre, Hamilton has a great demand for health care practitioners. Led by a world-class faculty, Mohawk prepares students in outstanding facilities that include the human anatomy and simulation labs, as well as computer and digital labs. You’ll complete field and clinical placements with teaching and community hospitals throughout Ontario for enhanced learning in a real health care setting.",
    lat: 43.2595568,
    lng: -79.9202938,
  },
  {
    src: "https://www.mohawkcollege.ca/sites/default/files/Campuses%20and%20Maps/mississauga-campus-v2-820x370psd.png",
    h2: "Mississauga Campus",
    h3: "About Mississauga Campus:",
    p: "Through a partnership agreement with triOS College, a registered private career college, Mohawk College offers International students the opportunity to earn a Mohawk College credential at triOS College’s Mississauga campus. This new, modern campus is located in the heart of Mississauga at Square One Shopping Centre, the largest shopping centre in Ontario.",
    lat: 43.5926416,
    lng: -79.6436888,
  },
  {
    src: "https://www.mohawkcollege.ca/sites/default/files/2016-07/osttc-exterior-700x467.jpg",
    h2: "Ogwehoweh Skills and Trades Training Centre (OC):",
    h3: "About Ogwehoweh Campus:",
    p: "Located north of the intersection of Fourth Line and Chiefswood Road.",
    lat: 43.07069643728413,
    lng: -80.1154412332504,
  },
  {
    src: "https://www.mohawkcollege.ca/sites/default/files/Campuses%20and%20Maps/SNP-Brantford-campus-846x564.jpg",
    h2: "Six Nations Polytechnic - Brantford (SB):",
    h3: "About Brantford Campus",
    p: "Six Nations Polytechnic, Brantford Campus, gives students the opportunity to study select Mohawk College programs while staying close to home.",
    lat: 43.151951422804096,
    lng: -80.22432304561082,
  },
  {
    src: "https://www.mohawkcollege.ca/sites/default/files/2016-11/Exterior-Six-Nations-Campus-800x533.jpg",
    h2: "Six Nations Polytechnic - Ohsweken (SN):",
    h3: "About Ogwehoweh Campus:",
    p: "Mohawk College, in partnership with Six Nations Polytechnic, is proud to offer programs and services to Indigenous communities.",
    lat: 43.05985878878612,
    lng: -80.09973630328571,
  },
  {
    src: "https://www.mohawkcollege.ca/sites/default/files/Campuses%20and%20Maps/sc-frontshot-820x370.jpg",
    h2: "Stoney Creek Campus for Skilled Trades (SC):",
    h3: "About Stoney Creek Campus:",
    p: "Mohawk's Stoney Creek Campus for Skilled Trades is the home of the Marshall School of Skilled Trades & Apprenticeship. With top technology and professional facilities for skilled trades, Mohawk grads are in high demand. Our well-prepared apprentices choose from a lineup of eager industry employers. At Mohawk College, you’ll obtain job-ready training and in-school education to step into tomorrow’s workforce. Apprentices are in great demand in a highly competitive global market that has to meet the challenges of today’s technology. Mohawk annually serves 2,400 apprenticeship students and is one of the largest trainers of apprentices in Ontario.",
    lat: 43.22686189060394,
    lng: -79.71266775725526,
  },
  {
    src: "https://www.mohawkcollege.ca/sites/default/files/Campuses%20and%20Maps/tansley-820x500.jpg",
    h2: "Tansley Woods - Schlegel:",
    h3: "About Tansley Woods",
    p: "Mohawk College's new campus located at The Village of Tansley Woods provides students the opportunity to study and learn in a retirement and long term care environment. Visit our blog to learn more about studying at the Tansley Woods Living Classroom.",
    lat: 43.38317611306715,
    lng: -79.79895320326955,
  },
  {
    src: "https://www.mohawkcollege.ca/sites/default/files/Marketing%20and%20Communications/images/campus-wentworth-heights-schlegel.jpg",
    h2: "Wentworth Heights - Schlegel:",
    h3: "About Wentworth Heights",
    p: "In addition to the Institute for Applied Health Sciences at McMaster intake, we also have a Wentworth Heights – Schlegel intake for the Personal Support Worker (110) program.",
    lat: 43.1985721370609,
    lng: -79.87360117444369,
  }
];
